name: Deploy to Amazon Web Services EC2

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn' # Cache Yarn packages

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Restart pm2 Job
        run: pm2 restart server --update-env
